[env]
TERM = "alacritty"

[font]
normal = { family = "Iosevka Term Nerd Font", style = "" }
#bold = { family = "Iosevka Term", style = "Bold" }
#italic = { family = "Iosevka Term", style = "Regular" }
size = 15

[window]
startup_mode = "Maximized"
decorations = "None"
opacity = 1

[scrolling]
history = 100000

[colors]
primary = { foreground = "#bbbbbb", background = "#000000" }
cursor = { cursor = "#6287b5", text = "#000000" }

[keyboard]
bindings = [
    { key = "j", mods = "Control | Shift",  action = "IncreaseFontSize" },
    { key = "k", mods = "Control | Shift",  action = "DecreaseFontSize" },
    { key = "ö", mods = "Control | Shift",  action = "ResetFontSize" },
]
