[env]
TERM = "alacritty"

[font]
normal = { family = "Iosevka Term", style = "Regular" }
size = 17

[window]
startup_mode = "Maximized"
decorations = "None"
opacity = 0.84

[colors]
primary = { foreground = "#bbbbbb", background = "#000000" }
cursor = { cursor = "#b3a084", text = "#000000" }

[keyboard]
bindings = [
    { key = "j", mods = "Control | Shift",  action = "IncreaseFontSize" },
    { key = "k", mods = "Control | Shift",  action = "DecreaseFontSize" },
    { key = "ö", mods = "Control | Shift",  action = "ResetFontSize" },
]
