#Font
font_family JetBrains Mono
italic_font auto
bold_font auto
bold_italic_font auto
font_size 13

# Theme
foreground #cccccc
background #000000
url_color #d65c9d

cursor #dddddd
cursor_text_color background
cursor_shape block
cursor_blink_interval 0.5
shell_integration no-cursor

enable_true_color true
term tmux-256color
background_opacity 1
hide_window_decorations no

