#font=Agave:size=17:style=slashed
#font=Monoid:size=13
#font=JetBrains Mono:size=15:style=Medium
#font=Martian Mono:size=14:style=Cn Lt
#font=Anonymous Pro:size=17:style=Bold
#font=M+ 1m:size=15:style=medium
#font=Crystal:size=15
#font=Inconsolata Condensed:size=15
#font=Audio Link Mono:size=17:style=Bold
#font=Noto Sans Mono Condensed:size=20
#font=RobotoMono Nerd Font:size=15:style=Medium
#font=Fira Code:size=15:style=Medium
#font=Lotion:size=17:style=SemiBold

font=Victor Mono:size=15:style=SemiBold
font-bold=Victor Mono:size=15:style=Bold
#font=Iosevka Term Nerd Font Mono:size=15:style=Medium
initial-color-theme=dark

font-size-adjustment=1.5
initial-window-mode=maximized

[colors-dark]
alpha=1
background=000000
foreground=dddddd
cursor=000000 b4d173

regular0=000000
regular1=cc6666
regular2=b5bd68
regular3=f0c674
regular4=81a2be
regular5=b294bb
regular6=8abeb7
regular7=c5c8c6

bright0=969896
bright1=cc6666
bright2=b5bd68
bright3=f0c674
bright4=81a2be
bright5=b294bb
bright6=8abeb7
bright7=bbbbbb

[colors-light]
foreground=000000
background=eeeeee
cursor=eeeeee 3a8cbc
selection-foreground=000000
selection-background=d7d7d7

# Normal colors
regular0=eeeeee
regular1=a8334c
regular2=4f6c31
regular3=944927
regular4=286486
regular5=88507d
regular6=3b8992
regular7=353535

# Bright colors
bright0=c6c3c3
bright1=94253e
bright2=3f5a22
bright3=803d1c
bright4=1d5573
bright5=7b3b70
bright6=2b747c
bright7=5c5c5c


[key-bindings]
font-increase=Control+Shift+j
font-decrease=Control+Shift+k
font-reset=Control+Shift+odiaeresis
