#font=Fira Code:size=14:style=Medium
#line-height=17
#font=Agave:size=17:style=slashed
#font=Martian Mono:size=14:style=Cn Lt
#font=Anonymous Pro:size=17
font=Iosevka Term Nerd Font Mono:size=17:style=Regular
#line-height=20
#letter-spacing=-1px
font-size-adjustment=1.5
initial-window-mode=maximized

[colors-dark]
alpha=1
background=000000
foreground=cccccc
cursor=000000 6287b5

regular0=000000
regular1=cc6666
regular2=b5bd68
regular3=f0c674
regular4=81a2be
regular5=b294bb
regular6=8abeb7
regular7=c5c8c6

bright0=969896
bright1=cc6666
bright2=b5bd68
bright3=f0c674
bright4=81a2be
bright5=b294bb
bright6=8abeb7
bright7=bbbbbb

[key-bindings]
font-increase=Control+Shift+j
font-decrease=Control+Shift+k
font-reset=Control+Shift+odiaeresis
