#!/bin/bash
wlr-randr --output DP-1 --mode 2560x1440@239.992004Hz
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=wlr
updatedwlb &
swaybg -i ~/Pictures/wp10907424-thomas-cole-wallpapers.jpg &
dwlb
