# color setup

set -g default-terminal "screen-256color"
set -ga terminal-overrides ',xterm-256colorc:Tc'
# set -g terminal-overrides ',kitty-256color:Tc'
# set-option -g allow-rename off

set -g mouse on

# status bar style
set-option -g status-position top
set -g status-style 'fg=#cccccc bg=#202020' #| blue 149fff

set -g status-left-length 45
set -g status-left "[#S] > "

set -g status-justify left
setw -g window-status-current-style 'fg=#dddddd bg=#3d3d3d'
setw -g window-status-current-format ' #I '

setw -g window-status-format ' #I '
setw -g window-status-style 'fg=#bbbbbb'

set -g status-right-length 45
set -g status-right "[%H:%M]"
set -g status-right-style ''

# pane style
set -g pane-border-style 'fg=#CCCCCC'
set -g pane-active-border-style 'fg=#ff880a'

# windows
set -g base-index 1
set -g renumber-windows on

# get rid of vim lag'
set -s escape-time 0

# Key bindings
set -g prefix C-s
bind r source-file ~/.tmux.conf

bind c new-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind o split-window -v -c "#{pane_current_path}"
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

bind-key -n M-0 select-window -t 0
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9

unbind -n Tab
setw -g mode-keys vi
bind-key -T root M-i copy-mode
bind-key -n C-f run-shell "tmux neww ~/.scripts/tmux_session.sh"
