#Font
font_family family="Iosevka Term" style="Light"
italic_font auto
bold_font Iosevka Term Medium
bold_italic_font Iosevka Term Medium Italic
font_size 15
disable_ligatures cursor
modify_font cell_width 100%
modify_font cell_height 100%
# text_composition_strategy legacy

# Theme
cursor #bbbbbb
cursor_shape beam
foreground #bbbbbb
background #000000
url_color #d65c9d

color0 #51576d
color1 #e78284
color2 #a6d189
color3 #e5c890
color4 #8caaee
color5 #f4b8e4
color6 #81c8be
color7 #a5adce
color8 #626880
color9 #e67172
color10 #8ec772
color11 #d9ba73
color12 #7b9ef0
color13 #f2a4db
color14 #5abfb5
color15 #b5bfe2

# Misc
cursor_text_color background
cursor_shape block
# cursor_blink_interval 0.5
# cursor_trail 1
# cursor_trail_decay 0 0.05
shell_integration no-cursor

background_opacity 0.9
hide_window_decorations yes
enable_audio_bell no

map ctrl+shift+j change_font_size all +1.0
map ctrl+shift+k change_font_size all -1.0
map ctrl+shift+ö restore_font_size
