#Font
font_family family="Iosevka Term" style=Light
italic_font auto
bold_font JetBrains Mono Medium
bold_italic_font JetBrains Mono Medium Italic
font_size 15
disable_ligatures cursor
modify_font cell_width 105%
modify_font cell_height 95%
# text_composition_strategy legacy

# Theme
cursor #bbbbbb
cursor_shape beam
foreground #bbbbbb
background #000000
url_color #d65c9d

# normal
color0 #000000
color1 #5f8787
color2 #bf8fb5
color3 #a87da0
color4 #888888
color5 #999999
color6 #aaaaaa
color7 #c1c1c1

# bright
color8 #333333
color9 #5f8787
color10 #bf8fb5
color11 #a87da0
color12 #888888
color13 #999999
color14 #aaaaaa
color15 #c1c1c1

# Misc
cursor_text_color background
cursor_shape block
# cursor_blink_interval 0.5
# cursor_trail 1
# cursor_trail_decay 0 0.05
shell_integration no-cursor

background_opacity 1
hide_window_decorations yes
enable_audio_bell no

map ctrl+shift+j change_font_size all +1.0
map ctrl+shift+k change_font_size all -1.0
map ctrl+shift+ö restore_font_size
