#Font
font_family family="JetBrains Mono" style=ExtraLight
italic_font auto
bold_font auto
bold_italic_font auto
font_size 13
disable_ligatures cursor

# Theme
foreground #dddddd
background #000000
url_color #d65c9d

cursor #dddddd
cursor_text_color background
cursor_shape block
cursor_blink_interval 0.5
shell_integration no-cursor

background_opacity 1
hide_window_decorations yes
enable_audio_bell no

map ctrl+shift+j increase_font_size
map ctrl+shift+k decrease_font_size
map ctrl+shift+ö restore_font_size
